# gradle.properties
# Magic Sushi — JVM 参数 + AndroidX 开关

# AndroidX
android.useAndroidX=true
# 自动映射旧 support 库到 AndroidX
android.enableJetifier=false

# Kotlin 编码风格
kotlin.code.style=official

# JVM 参数（Gradle 守护进程）
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# 关闭无用特性加速构建
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=true
